<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETP.TemplatesManagement.Data\ETP.TemplatesManagement.Data.csproj" />
    <ProjectReference Include="..\ETP.TemplatesManagement.RA\ETP.TemplatesManagement.RA.csproj" />
    <ProjectReference Include="..\ETP.TemplatesManagement.SDK\ETP.TemplatesManagement.SDK.csproj" />
  </ItemGroup>

</Project>
